### ISSUE TITLE
There is no date on the post page.

### ISSUE THREAD

**Issue by JeroenKnoops** [040code/040code.github.io#15]
There is no date on the post page, only on the listing page. 

This makes it hard for people to value the post, because people tend to want to now how old a post is.

**Comment by npalm** [comment]
@JeroenKnoops Where should we put the date of a post, any suggestion?

**Comment by JeroenKnoops** [comment]
Something like: 
<img width="887" alt="screen shot 2017-09-22 at 11 37 40" src="https://user-images.githubusercontent.com/10019/30738472-82c96842-9f8a-11e7-9a41-96b743d9b8dd.png">
